package controllers

import (
	"fmt"
	"strings"

	stroomv1 "github.com/gradata-systems/stroom-k8s-operator/api/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	ctrl "sigs.k8s.io/controller-runtime"
)

const (
	NginxMtlsPortNumber      = 443
	NginxMtlsPortName        = "mtls-https"
	NginxMtlsDefaultImage    = "nginx:stable-alpine"
	NginxMtlsDefaultReplicas = int32(2)
	NginxTlsVolumeName       = "nginx-tls"
	NginxCaVolumeName        = "nginx-ca"
	NginxConfVolumeName      = "nginx-conf"
)

// nginxConf generates the nginx.conf content for mTLS termination.
// It creates an upstream block for each processing NodeSet service and
// proxies all requests to Stroom's HTTP port, forwarding the client cert as X-SSL-CERT.
func nginxConf(stroomCluster *stroomv1.StroomCluster, hasCa bool) string {
	mtls := stroomCluster.Spec.Ingress.Mtls

	// Build upstream servers from all non-frontend NodeSet services
	var upstreamServers []string
	for i := range stroomCluster.Spec.NodeSets {
		nodeSet := &stroomCluster.Spec.NodeSets[i]
		if nodeSet.Role != stroomv1.FrontendNodeRole && nodeSet.IngressEnabled {
			svcName := stroomCluster.GetNodeSetServiceName(nodeSet)
			upstreamServers = append(upstreamServers, fmt.Sprintf("        server %v:%v;", svcName, AppHttpPortNumber))
		}
	}
	// Fall back to all NodeSets if no explicit processing nodes found
	if len(upstreamServers) == 0 {
		for i := range stroomCluster.Spec.NodeSets {
			nodeSet := &stroomCluster.Spec.NodeSets[i]
			if nodeSet.IngressEnabled {
				svcName := stroomCluster.GetNodeSetServiceName(nodeSet)
				upstreamServers = append(upstreamServers, fmt.Sprintf("        server %v:%v;", svcName, AppHttpPortNumber))
			}
		}
	}

	sslVerifyClient := "optional_no_ca"
	caBlock := ""
	if hasCa {
		sslVerifyClient = "optional"
		caBlock = "        ssl_client_certificate /etc/nginx/ca/ca.crt;\n"
	}

	_ = mtls // settings available for future extension

	return fmt.Sprintf(`# nginx mTLS terminator — generated by stroom-k8s-operator
events {}

http {
    upstream stroom_backend {
%v
    }

    server {
        listen %v ssl;
        server_name _;

        # Server TLS certificate
        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        # Client certificate verification
        ssl_verify_client %v;
%v

        # Large body support for datafeed uploads
        client_max_body_size 0;
        proxy_request_buffering off;

        location / {
            proxy_pass       http://stroom_backend;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            # Forward the URL-encoded PEM client certificate to Stroom
            proxy_set_header X-SSL-CERT        $ssl_client_escaped_cert;
        }
    }
}
`,
		strings.Join(upstreamServers, "\n"),
		NginxMtlsPortNumber,
		sslVerifyClient,
		caBlock,
	)
}

// createNginxMtlsConfigMap creates a ConfigMap containing the nginx.conf for mTLS termination.
func (r *StroomClusterReconciler) createNginxMtlsConfigMap(stroomCluster *stroomv1.StroomCluster) *corev1.ConfigMap {
	mtls := stroomCluster.Spec.Ingress.Mtls
	hasCa := mtls.CaSecretName != ""

	configMap := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      stroomCluster.GetNginxMtlsName(),
			Namespace: stroomCluster.Namespace,
			Labels:    stroomCluster.GetLabels(),
		},
		Data: map[string]string{
			"nginx.conf": nginxConf(stroomCluster, hasCa),
		},
	}

	ctrl.SetControllerReference(stroomCluster, configMap, r.Scheme)
	return configMap
}

// createNginxMtlsDeployment creates the nginx Deployment that terminates mTLS.
func (r *StroomClusterReconciler) createNginxMtlsDeployment(stroomCluster *stroomv1.StroomCluster) *appsv1.Deployment {
	mtls := stroomCluster.Spec.Ingress.Mtls
	name := stroomCluster.GetNginxMtlsName()
	replicas := NginxMtlsDefaultReplicas

	image := mtls.Image
	if image == "" {
		image = NginxMtlsDefaultImage
	}

	// Always mount the nginx.conf ConfigMap and the TLS server cert secret
	volumes := []corev1.Volume{
		{
			Name: NginxConfVolumeName,
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{Name: name},
				},
			},
		},
		{
			Name: NginxTlsVolumeName,
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{
					SecretName: mtls.TlsSecretName,
				},
			},
		},
	}

	volumeMounts := []corev1.VolumeMount{
		{
			Name:      NginxConfVolumeName,
			MountPath: "/etc/nginx/nginx.conf",
			SubPath:   "nginx.conf",
			ReadOnly:  true,
		},
		{
			Name:      NginxTlsVolumeName,
			MountPath: "/etc/nginx/tls",
			ReadOnly:  true,
		},
	}

	// Optionally mount the CA secret for client cert verification
	if mtls.CaSecretName != "" {
		volumes = append(volumes, corev1.Volume{
			Name: NginxCaVolumeName,
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{
					SecretName: mtls.CaSecretName,
				},
			},
		})
		volumeMounts = append(volumeMounts, corev1.VolumeMount{
			Name:      NginxCaVolumeName,
			MountPath: "/etc/nginx/ca",
			ReadOnly:  true,
		})
	}

	labels := stroomCluster.GetLabels()
	labels["app.kubernetes.io/component"] = "mtls-nginx"

	deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: stroomCluster.Namespace,
			Labels:    labels,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					stroomv1.StroomClusterLabel:   stroomCluster.Name,
					"app.kubernetes.io/component": "mtls-nginx",
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						stroomv1.StroomClusterLabel:   stroomCluster.Name,
						"app.kubernetes.io/component": "mtls-nginx",
					},
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{
						Name:            "nginx",
						Image:           image,
						ImagePullPolicy: corev1.PullIfNotPresent,
						Ports: []corev1.ContainerPort{{
							Name:          NginxMtlsPortName,
							ContainerPort: NginxMtlsPortNumber,
							Protocol:      corev1.ProtocolTCP,
						}},
						VolumeMounts: volumeMounts,
						ReadinessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{
								TCPSocket: &corev1.TCPSocketAction{
									Port: intstr.FromInt(NginxMtlsPortNumber),
								},
							},
							InitialDelaySeconds: 5,
							PeriodSeconds:       10,
						},
						LivenessProbe: &corev1.Probe{
							ProbeHandler: corev1.ProbeHandler{
								TCPSocket: &corev1.TCPSocketAction{
									Port: intstr.FromInt(NginxMtlsPortNumber),
								},
							},
							InitialDelaySeconds: 10,
							PeriodSeconds:       20,
						},
					}},
					Volumes: volumes,
				},
			},
		},
	}

	ctrl.SetControllerReference(stroomCluster, deployment, r.Scheme)
	return deployment
}

// createNginxMtlsService creates a ClusterIP Service exposing nginx on port 443.
// The HAProxy passthrough Ingress routes to this Service.
func (r *StroomClusterReconciler) createNginxMtlsService(stroomCluster *stroomv1.StroomCluster) *corev1.Service {
	name := stroomCluster.GetNginxMtlsName()

	service := &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: stroomCluster.Namespace,
			Labels:    stroomCluster.GetLabels(),
		},
		Spec: corev1.ServiceSpec{
			Type: corev1.ServiceTypeClusterIP,
			Selector: map[string]string{
				stroomv1.StroomClusterLabel:   stroomCluster.Name,
				"app.kubernetes.io/component": "mtls-nginx",
			},
			Ports: []corev1.ServicePort{{
				Name:       NginxMtlsPortName,
				Port:       NginxMtlsPortNumber,
				TargetPort: intstr.FromInt(NginxMtlsPortNumber),
				Protocol:   corev1.ProtocolTCP,
			}},
		},
	}

	ctrl.SetControllerReference(stroomCluster, service, r.Scheme)
	return service
}
